# [nvim-transparent]
# src.git = "https://github.com/xiyaowong/nvim-transparent"
# fetch.github = "xiyaowong/nvim-transparent"

[nvim-base-16]
src.git = "https://github.com/RRethy/nvim-base16"
fetch.github = "RRethy/nvim-base16"
