[nvim-transparent]
src.git = "https://github.com/xiyaowong/nvim-transparent"
fetch.github = "xiyaowong/nvim-transparent"

[nvim-base-16]
src.git = "https://github.com/RRethy/nvim-base16"
fetch.github = "RRethy/nvim-base16"

[hlargs]
src.git = "https://github.com/m-demare/hlargs.nvim"
fetch.github = "m-demare/hlargs.nvim"

[org-bullets-nvim]
src.git = "https://github.com/nvim-orgmode/org-bullets.nvim"
fetch.github = "nvim-orgmode/org-bullets.nvim"
