[buildPlans.iosevka-normal]
family = "iosevka-normal"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-normal.variants]
  inherits = "ss14"

  [buildPlans.iosevka-normal.ligations]
  inherits = "dlig"

  [buildPlans.iosevka-normal.variants.design]
    zero = "slashed"

[buildPlans.iosevka-normal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-normal.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-normal.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-normal.weights.bold]
shape = 700
menu = 700
css = 700
