name: "Flake cache"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Flake Check"]
    types:
      - completed

jobs:
  main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: cachix/install-nix-action@v16
      name: Install Nix unstable
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.8.0pre20220311_d532269/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-substituters = https://viperml.cachix.org
          extra-trusted-public-keys = viperml.cachix.org-1:qZhKBMTfmcLL+OG6fj/hzsMEedgKvZVFRRAhq7j8Vh8=
          extra-substituters = https://nix-community.cachix.org
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    - uses: cachix/cachix-action@v10
      name: Login to Cachix
      with:
        name: viperml
        extraPullNames: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Cache flake inputs
      run: nix flake archive
    - name: Cache devShell
      run: nix build .#devShells.x86_64-linux.default.inputDerivation
    - name: Cache overlays/pkgs-*
      run: nix run .#pkgs.python3 -- ./bin/pkgs_build.py
