name: "g-neovim release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: cachix/install-nix-action@v16
      name: Install Nix unstable
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.8.0pre20220311_d532269/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-substituters = https://viperml.cachix.org
          extra-trusted-public-keys = viperml.cachix.org-1:qZhKBMTfmcLL+OG6fj/hzsMEedgKvZVFRRAhq7j8Vh8=
          extra-substituters = https://nix-community.cachix.org
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    - run: nix run .#python3 -- ./bin/g-neovim-release.py
      name: Bundle g-neovim
    - uses: actions/upload-artifact@v3
      name: Upload drvPath
      with:
        name: drvPath
        path: results/drvPath
    - uses: actions/upload-artifact@v3
      name: Upload RPM
      with:
        name: g-neovim.rpm
        path: results/*.rpm
    - uses: actions/upload-artifact@v3
      name: Upload DEB
      with:
        name: g-neovim.deb
        path: results/*.deb
