name: Update all

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.matrix.outputs.paths }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix
      uses: ./.github/actions/install-nix

    - name: Generate matrix
      run: echo "paths=$(nix run .#dotfiles-update-matrix)" >> $GITHUB_OUTPUT
      id: matrix

  update_element:
    runs-on: ubuntu-latest
    needs: [matrix]
    if: ${{ needs.matrix.outputs.paths != '[]' && needs.matrix.outputs.paths != '' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.matrix.outputs.paths )}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Update element
      run: nix run .#dotfiles-update-nv -- ${{ matrix.path }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: '${{ secrets.PAT }}'
        title: 'ci: bump ${{ matrix.path }}'
        commit-message: |
          Bump ${{ matrix.path }}


          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: GitHub <noreply@github.com>
        branch: update//${{ matrix.path }}
        delete-branch: true
