name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 */15 * *"

jobs:
  flake_update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Flake update
      run: nix flake update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        title: '[automatic] flake update'
        commit-message: |
          Automatic flake update
        body: |
          Automatic flake update
        branch: update-flake
        branch-suffix: timestamp
        delete-branch: true

  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.find_scripts.outputs.scripts }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - id: find_scripts
      name: Find updater scripts
      run: nix run .#python3 -- ./bin/update_generate_matrix.py

  update:
    runs-on: ubuntu-latest
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        script: ${{fromJson(needs.generate_matrix.outputs.scripts)}}
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Setup dependencies
      run: |
        nix profile install \
          .#nix-prefetch \
          .#update-nix-fetchgit \
          .#nix-update \
          .#git-extras
    - name: Run update script
      run: |
        cd $(dirname ${{ matrix.script }})
        sh -c "./$(basename ${{ matrix.script }})"
    - name: Get date
      run: echo "DATE=$(date --rfc-3339=date)" >> $GITHUB_ENV
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        title: '[automatic] script update ${{ matrix.script }}'
        commit-message: |
          Automatic update for ${{ matrix.script }}
        body: |
          Beep-bop: I ran the update script sucessfully
        branch: update-script
        branch-suffix: random
        delete-branch: true
